using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class camera1 : MonoBehaviour
{
    // ŠŠ‘lèË•q“x
    public float sensitivityHor = 5f;
    public float sensitivityVer = 3f;
    // ã‰ºÅ‘å‹Šp
    public float upper = -60f;
    // ã‰ºÅ¬‹Šp
    public float downver = 60f;
    // ùçzŠp“x
    public float rotver;

    [SerializeField] GameObject Gun;
    [SerializeField] Transform bull_point;
    void Start()
    {
        //“¾“ã…x²çz“IŠp“xC–çA¥ã‰º‹Šp“IŠp“x
        rotver = transform.eulerAngles.x;
        //èªåUŠŠ‘l
        Cursor.visible = false;
    }

    void Update()
    {
        // Šl“¾ŠŠ‘l“IÀ•W
        float mouseHor = Input.GetAxis("Mouse X");
        float mouseVer = Input.GetAxis("Mouse Y");
        // ŒvZùçzŠp“xCŠŠ‘lŒüã¥‹ŠpŒü‰ºC”½”VC‘Š”½B
        rotver -= mouseVer * sensitivityVer;
        //’²®ã‰º‹Šp“I”Íš¡C–h~‘Š‹@çz‰ß“ª
        rotver = Mathf.Clamp(rotver, upper, downver);

        //T§‘Š‹@“Iã‰º‹ŠpC‘Š›”‰—•ƒ•¨Œ(Šß‰Æ)Cã…x²ùçz
        transform.localEulerAngles = new Vector3(rotver, 0, 0);
        //‹Špã‰º“®C‘„–ç—v“®
        Gun.transform.localEulerAngles = new Vector3(rotver, 0, 0);
        //‹Špã‰º“®Cá¢Ëqœ[ˆÊ’u–ç—v“®
        bull_point.localEulerAngles = new Vector3(rotver, 0, 0);
        //‘Š‹@“I¶‰E‹Šp
        transform.parent.Rotate(Vector3.up * mouseHor);

        //èªåUŠŠ‘l
        //Cursor.visible = false;
    }
}